[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"


[context.docs]
  base = "docs"
  publish = "build/"
  command = "npm run build"
    environment = { NODE_VERSION="16.16.0" }


[context.main]
  base = "docs"
  publish = "build/"
  command = "npm run build"
    environment = { NODE_VERSION="16.16.0" }
